### ISSUE TITLE
[V10 Beta] Call Lightning does not spawn at will bonus action in character sheet.

### ISSUE THREAD

**Issue by KonteiKeisei** [Vauryx/advancedspelleffects#136]
FoundryV10 10.291
Midi 10.0.29
DND5E 2.1.4

Console Error:
`Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading '0')
[Detected 1 package: advancedspelleffects]
    at callLightning.createStormCloud (setup.js:12098:54)
    at async ASEHandler.handleASE (setup.js:25520:11)`

**Comment by KonteiKeisei** [comment]
ASE version: 0.9.!9.93

**Comment by KonteiKeisei** [comment]
Looks like its an error with this line here:
`    let newDamageNum = Number(castItemDamage.parts[0][0][0]) + (spellLevel - 3) + (stormyWeather ? 1 : 0);`
